# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1579295c7a01c727a88126882985a32026a07dd2e8de3bed63805328a14bf3796d96e00f06084866907c4abbbebf7e15ab949e38905cf28afa9fd3effffb1d15

test:
  secret_key_base: ac18daed136d4e7d1dda72b3a674e072ff04e103e37841c558c9aa288feb2d2f0154cdcae4e0c81900f471f0b1076d4fb97b10b063fd36adb6cb9ed55fd198ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
